GET http://localhost:3001/api/v1/scholarships

###

GET http://localhost:3001/api/v1/scholarships/1

###

GET http://localhost:3001/api/v1/scholarships/filter/?category=national

###

POST http://localhost:3001/api/v1/scholarships
Content-Type: application/json

{
  "name": "beca4",
  "percentage": 67,
  "category": "national",
  "requirements": ["this is incredible"]
}

###

PUT http://localhost:3001/api/v1/scholarships/3
Content-Type: application/json

{
  "name": "beca4 updated",
  "percentage": 89,
  "category": "national",
  "requirements": ["this is incredible"]
}

###

DELETE http://localhost:3001/api/v1/scholarships/1

###

GET http://localhost:3001/api/v1/scholarships-mysql

###

GET http://localhost:3001/api/v1/scholarships-mysql/2

###

POST http://localhost:3001/api/v1/scholarships-mysql
Content-Type: application/json

{
  "name": "beca4",
  "percentage": 95,
  "category": "national"
}

###

GET http://localhost:3001/api/v1/users-mysql

###

GET http://localhost:3001/api/v1/users-mysql/1

###

POST http://localhost:3001/api/v1/users-mysql
Content-Type: application/json

{
  "fullname": "user2",
  "email": "user2@gmail.com",
  "password": "root123",
  "role": "user",
  "scholarship": 3
}

###

PUT http://localhost:3001/api/v1/users-mysql/2
Content-Type: application/json

{
  "fullname": "user2 update name",
  "email": "user2@gmail.com",
  "password": "root123",
  "role": "user",
  "scholarship": 3
}
